
subinclude("//build_defs:cc")

cc_library(
    name = "TestLib2",
    srcs=["libSource2.cpp"],
    hdrs=["libHeader2.h"],
    includes=["testFolder"],
    defines=["TEST_DEFINE"],
    visibility=["PUBLIC"]
)