

filegroup(
    name = "cc",
    srcs = ["cc.build_defs"],
    visibility = ["PUBLIC"]
)

filegroup(
    name = "c",
    srcs = ["c.build_defs"],
    visibility = ["PUBLIC"]
)

filegroup(
    name = "gcc",
    srcs = ["gcc.build_defs"],
    visibility = ["PUBLIC"]
)